### ISSUE TITLE
Block Data Provider using Bitcoin Core RPC

### ISSUE THREAD

**Issue by theanmolsharma** [Bitshala-Incubator/silent-pay-indexer#12]
### Overview
A block data provider that connects to a Bitcoin Core Full Node and creates indexes.

### Constraints
- [`txindex`](https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch03.asciidoc#txindex) should not be required for the Bitcoin node

### RPCs that could be used to sync
- [`getblock`](https://developer.bitcoin.org/reference/rpc/getblock.html) with `verbosity = 2`
- [`getrawtransaction`](https://developer.bitcoin.org/reference/rpc/getrawtransaction.html) with `verbose = true` and `blockhash`

### Implementation Details
- Block Provider should emit [`IndexTransactionCommand`](https://github.com/Bitshala-Incubator/silent-pay-indexer/blob/33c988312aa24fd66958e836fe9fef7a78e5b702/src/commands/impl/index-transaction.command.ts#L14C14-L14C37) with the necessary data
- Add another command called `IndexBlockCommand` and it's handler.
- This block provider should use `IndexBlockCommand`.

**Comment by aruokhai** [comment]
Taking this.
