### ISSUE TITLE
Implement Retry Mechanism for Failed Requests in EsploraProvider

### ISSUE THREAD

**Issue by theanmolsharma** [Bitshala-Incubator/silent-pay-indexer#17]
In the current implementation of the `EsploraProvider` class, the `request` method does not retry the request if a server error occurs.

We should implement a retry mechanism in the `request` method. The retry mechanism should handle server errors (HTTP status codes 5xx) and network errors, and should have a limit on the number of retry attempts to prevent infinite loops.

**Comment by aruokhai** [comment]
Taking this

**Comment by theanmolsharma** [comment]
Merged in #20
