### ISSUE TITLE
Add `batchSize` configuration option for parallelizing requests in EsploraProvider

### ISSUE THREAD

**Issue by theanmolsharma** [Bitshala-Incubator/silent-pay-indexer#18]
In the current implementation of the `EsploraProvider` class, the `processBlock` method processes transactions sequentially. This can be inefficient, especially when dealing with blocks on mainnet that contain a large number of transactions.

We should do the following:
- add a new configuration option called `batchSize`
- when `batchSize` is set, the requests made in the `processBlock` method should be parallelized using `Promise.all()`. The size of each batch will be determined by the `batchSize` value.

TDB:
- set an upper limit on value of `batchSize`

This enhancement will improve the performance of the `processBlock` method by allowing it to process multiple transactions concurrently, reducing the overall time required to process a block.

**Comment by notTanveer** [comment]
i would like to work on this issue.

**Comment by theanmolsharma** [comment]
Fixed in #22
