### ISSUE TITLE
Create and endpoint to serve silent block for specific hash or height

### ISSUE THREAD

**Issue by theanmolsharma** [Bitshala-Incubator/silent-pay-indexer#19]
There is no dedicated endpoint to serve a silent block for a specific block hash or height.

This issue is to track the development of two new endpoints that serve a silent block for a given block hash and height. The endpoints should accept the block hash and the block height respectively. They should return the corresponding silent block in the format specified in the [`design.md`](https://github.com/Bitshala-Incubator/silent-pay-indexer/blob/main/docs/design.md#specification-for-silent-block) document.

This enhancement will allow clients to fetch all tweaks for a specific block.

**Comment by seekersoftec** [comment]
Taking this

**Comment by theanmolsharma** [comment]
Merged in #41
