### ISSUE TITLE
Add config validation

### ISSUE THREAD

**Issue by theanmolsharma** [Bitshala-Incubator/silent-pay-indexer#2]
Install and use `class-validator` to validate config in `configuration.ts`

**Comment by Nesopie** [comment]
Hey! Can I work on this?

**Comment by theanmolsharma** [comment]
of course, I'm assigning it to you. We can use the issue for discussion if you have any questions. We also have a weekly sync call [Discord](https://discord.com/events/1104831812720656540/1209759462768775168) on Tuesday which you can join.

**Comment by Nesopie** [comment]
thanks! I'll be sure to join it :)
