### ISSUE TITLE
Dependency installation requires `--force` flag

### ISSUE THREAD

**Issue by theanmolsharma** [Bitshala-Incubator/silent-pay-indexer#24]
Currently, the project requires the use of the `--force` flag when running `npm install`. This indicates that there are unresolved dependency conflicts or compatibility issues that need to be addressed. To ensure a smoother installation process and improve overall stability, we should identify and resolve these conflicts so that `npm install` can be run without any flags.

Tasks
- [ ] Identify conflicts by running `npm install` without the `--force flag`.
- [ ] Investigate the conflicting dependencies and update them to compatible versions.
- [ ] If any dependencies are outdated or deprecated, consider replacing them with actively maintained alternatives.
- [ ] Update the `README.md` to reflect any changes made to the dependencies.

Additional tasks
- [ ] Update vulnerable dependencies

**Comment by notTanveer** [comment]
taking this
